version: 2
updates:
  - package-ecosystem: npm
    directory: "/."
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    assignees:
      - HugoDF
